WorldBuilder/Models/Creator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorldBuilder.Models
{
    public class Creator
    {
        [Key]
        public int CreatorId { get; set; }
        //Add custom error message
        //https://stackoverflow.com/questions/6587816/how-to-change-the-errormessage-for-int-model-validation-in-asp-net-mvc
        [Required(ErrorMessage = "Please enter your first name."), StringLength(255), Display(Name = "First Name")]
        public string CreatorFName { get; set; }

        [Required(ErrorMessage = "Please enter your last name."), StringLength(255), Display(Name = "Last Name")]
        public string CreatorLName { get; set; }

        [Required(ErrorMessage = "Please enter your preferred display name."), StringLength(255), Display(Name = "Display Name")]
        public string CreatorDispName { get; set; }


        [Required(ErrorMessage = "Please enter a short bio about yourself."), StringLength(500), Display(Name = "Bio")]
        public string CreatorBio { get; set; }

        [StringLength(255), Display(Name = "Country of Origin")]
        public string CreatorOriginCountry { get; set; }

        public virtual ICollection<World> Worlds { get; set; }

    }
}

WorldBuilder/Controllers/CreatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorldBuilder.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Net;

namespace WorldBuilder.Controllers
{
    public class CreatorController : Controller
    {
        private WorldBuilderContext db = new WorldBuilderContext();

        // GET: Creator
        public ActionResult List()
        {            
            //Pass db object to view.
            //Referenced Christine's code.
            return View(db.Creators);
        }

        public ActionResult CreatorProfile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Creator creator = db.Creators.Find(id);
            if (creator == null)
            {
                return HttpNotFound();
            }
            return View(creator);
        }

        //If there is no POST, just return the view for Add.
        public ActionResult Add()
        {
            return View();
        }

        //After POST submission, the following code will run. The page is then redirected to List View
        //Reference Christine's Code.
        [HttpPost]
        //http://www.binaryintellect.net/articles/20e546b4-3ae9-416b-878e-5b12434fe7a6.aspx
        [ValidateAntiForgeryToken]
        public ActionResult Add(string CreatorFName, string CreatorLName, string CreatorDispName, string CreatorOriginCountry, string CreatorBio, Creator creator)
        {
            //If the input matches the model's constraint, execute the following query.
            //Else, show view, with error message.

            if (ModelState.IsValid)
            {
                string insertQuery = "insert into Creators (CreatorFName, CreatorLName, CreatorDispName, CreatorOriginCountry, CreatorBio) values (@CreatorFName, @CreatorLName, @CreatorDispName, @CreatorOriginCountry, @CreatorBio)";

                SqlParameter[] queryParams = new SqlParameter[5];
                queryParams[0] = new SqlParameter("@CreatorFName", CreatorFName);
                queryParams[1] = new SqlParameter("@CreatorLName", CreatorLName);
                queryParams[2] = new SqlParameter("@CreatorDispName", CreatorDispName);
                queryParams[3] = new SqlParameter("@CreatorOriginCountry", CreatorOriginCountry);
                queryParams[4] = new SqlParameter("@CreatorBio", CreatorBio);

                db.Database.ExecuteSqlCommand(insertQuery, queryParams);
                Debug.WriteLine(insertQuery);
                return RedirectToAction("List");
            }
            return View(creator);
        }

        public ActionResult EditCreator(int? id)
        {
            Creator creator = db.Creators.Find(id);

            return View(creator);
        }

        //Edit
        //Referenced Christine's code
        [HttpPost]
        public ActionResult EditCreator(int? CreatorId, string CreatorFName, string CreatorLName, string CreatorDispName, string CreatorOriginCountry, string CreatorBio)
        {
            string updateQuery = "update Creators set CreatorFName = @CreatorFName, CreatorLName = @CreatorLName, CreatorDispName = @CreatorDispName, CreatorOriginCountry = @CreatorOriginCountry, CreatorBio = @CreatorBio " +
                 "where CreatorId = @CreatorId";

            SqlParameter[] queryParams = new SqlParameter[6];
            queryParams[0] = new SqlParameter("@CreatorFName", CreatorFName);
            queryParams[1] = new SqlParameter("@CreatorLName", CreatorLName);
            queryParams[2] = new SqlParameter("@CreatorDispName", CreatorDispName);
            queryParams[3] = new SqlParameter("@CreatorOriginCountry", CreatorOriginCountry);
            queryParams[4] = new SqlParameter("@CreatorBio", CreatorBio);
            queryParams[5] = new SqlParameter("@CreatorId", CreatorId);

            db.Database.ExecuteSqlCommand(updateQuery, queryParams);
            Debug.WriteLine(updateQuery);
            return RedirectToAction("List");
        }

        //Delete - Referenced Christine's code.
        public ActionResult DeleteCreator(int id)
        {
            //Access ICollections WorldId.
            //Loop thorugh all world in Worlds by this creator.
            //Delete from image table where World_WorldId = WorldId.
            //This won't actually delete the image from the file...need to still handle that.
            var worldList = db.Creators.Find(id).Worlds;

            foreach (var world in worldList)
            {
                var worldId = world.WorldId;

                string queryString = "DELETE FROM images WHERE World_WorldID=@wid";
                SqlParameter param = new SqlParameter("@wid", worldId);

                db.Database.ExecuteSqlCommand(queryString, param);
            }

            string delWorldQuery = "delete from worlds where creator_creatorid = @id";
            db.Database.ExecuteSqlCommand(delWorldQuery, new SqlParameter("@id", id));


            string delCreatorQuery = "delete from creators where creatorid = @id";
            db.Database.ExecuteSqlCommand(delCreatorQuery, new SqlParameter("@id", id));

            //This method was finnicky as heck so I'll stick to using query strings.....
            //https://stackoverflow.com/questions/43257512/deleting-records-from-nested-tables-mvc-5
            //Delete from child table (worlds) before removing parent table (creators).
            //Creator creator = db.Creators.FirstOrDefault(c => c.CreatorId == id);

            //foreach (var item in creator.Worlds.ToList())
            //{
            //    foreach (var creators in item.Creator.Worlds.ToList())
            //    {
            //        db.Worlds.Remove(creators);
            //    }
            //    db.Worlds.Remove(item);
            //}

            //db.Creators.Remove(creator);
            db.SaveChanges();

            return RedirectToAction("List");
        }

        public ActionResult DeleteWorld(int id)
        {
            //Delete world 
            string delImgQuery = "delete from images where world_worldId = @id";
            db.Database.ExecuteSqlCommand(delImgQuery, new SqlParameter("@id", id));


            string delWorldQuery = "delete from worlds where worldId = @id";
            db.Database.ExecuteSqlCommand(delWorldQuery, new SqlParameter("@id", id));


            //https://stackoverflow.com/questions/43257512/deleting-records-from-nested-tables-mvc-5
            //Delete from child table (images) before removing parent table (world).
            //World world = db.Worlds.FirstOrDefault(w => w.WorldId == id);

            //foreach (var item in world.Images.ToList())
            //{   
            //    foreach (var worlds in item.World.Images.ToList())
            //    {
            //        db.Images.Remove(worlds);
            //    }
            //    db.Images.Remove(item);
            //db.Worlds.Remove(world);
            db.SaveChanges();
            //Redirect to previous link (ie creator profile).
            //https://stackoverflow.com/questions/815229/how-do-i-redirect-to-the-previous-action-in-asp-net-mvc
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

WorldBuilder/Controllers/WorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorldBuilder.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Net;

namespace WorldBuilder.Controllers
{
    public class WorldController : Controller
    {
        private WorldBuilderContext db = new WorldBuilderContext();

        // GET: World
        public ActionResult WorldList()
        {
            return View();
        }

        public ActionResult WorldDetails(int? id)
        {
            World world = db.Worlds.Find(id);

            return View(world);
        }


        public ActionResult AddWorld()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddWorld(string WorldName, string WorldOverview, string CreatorId, World world)
        {
            string insertQuery = "insert into Worlds (WorldName, WorldOverview, creator_CreatorId) values (@WorldName, @WorldOverview, @CreatorId)";
            //get id from url
            //https://stackoverflow.com/questions/24673292/get-id-from-url-in-an-action-from-a-controller-with-asp-net?rq=1
            //var creatorId = Url.RequestContext.RouteData.Values["id"];

            if (ModelState.IsValid)
            {
                SqlParameter[] queryParams = new SqlParameter[3];
                queryParams[0] = new SqlParameter("@WorldName", WorldName);
                queryParams[1] = new SqlParameter("@WorldOverview", WorldOverview);
                queryParams[2] = new SqlParameter("@CreatorId", CreatorId);

                db.Database.ExecuteSqlCommand(insertQuery, queryParams);
                Debug.WriteLine(insertQuery);
                return RedirectToAction("CreatorProfile/" + CreatorId, "Creator");
            }

            return View(world);
        }

        public ActionResult EditWorld(int id)
        {
            World world = db.Worlds.Find(id);

            return View(world);
        }

        [HttpPost]
        //Referenced from Christine's code! Thanks :D 
        public ActionResult EditWorld(int id, string WorldName, string WorldOverview, World world)
        {
            string updateQuery = "update Worlds set WorldName = @WorldName, WorldOverview = @WorldOverview where WorldId = @id";

            world = db.Worlds.Find(id);

            SqlParameter[] queryParams = new SqlParameter[3];
            queryParams[0] = new SqlParameter("@WorldName", WorldName);
            queryParams[1] = new SqlParameter("@WorldOverview", WorldOverview);
            queryParams[2] = new SqlParameter("@id", id);


            db.Database.ExecuteSqlCommand(updateQuery, queryParams);
            Debug.WriteLine(updateQuery);
            return RedirectToAction("WorldDetails/" + id);

        }

        public ActionResult AddImage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //handle file posting
        //https://stackoverflow.com/questions/16255882/uploading-displaying-images-in-mvc-4
        public ActionResult AddImage(Image image, int WorldId, HttpPostedFileBase file)
        {
            string insertQuery = "insert into Images (ImagePath, World_WorldId) values (@ImagePath, @WorldId)";

            if (ModelState.IsValid)
            {
                //If file is not empty, run the query.
                if (file != null)
                {
                    //Need to validate file type for images.

                    //Modify the filename to current date (year, month, day, minute, seconds) + file extension to create unique image file name.
                    //https://stackoverflow.com/questions/24625078/how-generate-a-unique-file-name-at-upload-files-in-webserver-mvc
                    var fileName = DateTime.Now.ToString("yyyymmddMMss") + System.IO.Path.GetExtension(file.FileName);

                    //Save the file in the root/Images/, and as its FileName.
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + fileName);

                    image.ImagePath = fileName;

                    SqlParameter[] queryParams = new SqlParameter[2];
                    queryParams[0] = new SqlParameter("@ImagePath", image.ImagePath);
                    queryParams[1] = new SqlParameter("@WorldId", WorldId);
                    db.Database.ExecuteSqlCommand(insertQuery, queryParams);
                    Debug.WriteLine(insertQuery);
                }
                db.SaveChanges();
                return RedirectToAction("WorldDetails/" + WorldId);
            }

            return RedirectToAction("AddImage/" + WorldId);
        }

    }
}

WorldBuilder/Views/Creator/CreatorProfile.cshtml
@model WorldBuilder.Models.Creator

@{
    ViewBag.Title = "Creator Profile";
}

<div class="mt-lg-3">
    <table>
        <tbody>
            <tr>
                <td>
                    <h1>@Html.DisplayFor(model => model.CreatorDispName)</h1>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Edit", "EditCreator", new { id = Model.CreatorId }) |
                    @Html.ActionLink("Delete", "DeleteCreator", new { id = Model.CreatorId }) |
                    @Html.ActionLink("Add World", "AddWorld", "World", new { id = Model.CreatorId }, new { })

                    @*@Html.ActionLink("linkText", "actionName", "controllerName",
                        new { /* routeValues forexample: id = 6 or leave blank or use null */ },
                        new { /* htmlAttributes forexample: @class = "my-class" or leave blank or use null */ })*@
                </td>
            </tr>
            <tr>
                <td></td>
            </tr>
        </tbody>
    </table>
    <div class="container m-lg-3">
        <nav>
            <div class="nav nav-tabs rounded-0" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active bg-info" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="true">Profile</a>
                <a class="nav-item nav-link" id="nav-worlds-tab" data-toggle="tab" href="#nav-worlds" role="tab" aria-controls="nav-worlds" aria-selected="false">Worlds</a>
                <a class="nav-item nav-link" id="nav-gallery-tab" data-toggle="tab" href="#nav-gallery" role="tab" aria-controls="nav-gallery" aria-selected="false">Gallery</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            @* PROFILE TAB *@
            <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                <div class="jumbotron border-0 bg-info">
                    <table class="mt-4">
                        <tbody>
                            <tr>
                                <td>
                                    <strong>Creator Name: </strong>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.DisplayFor(model => model.CreatorFName) @Html.DisplayFor(model => model.CreatorLName)
                                </td>
                            </tr>
                            <tr>
                                <td><strong>Country of Origin</strong></td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayFor(model => model.CreatorOriginCountry)</td>
                            </tr>
                            <tr>
                                <td><strong>Bio</strong></td>
                            </tr>
                            <tr>
                                <td>@Html.DisplayFor(model => model.CreatorBio)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            @* WORLD TAB *@
            <div class="tab-pane fade" id="nav-worlds" role="tabpanel" aria-labelledby="nav-worlds-tab">
                @foreach (var world in Model.Worlds)
                {

                    @* Create dynamic link to the creator's profile view *@
                    @*https://stackoverflow.com/questions/9584673/html-actionlink-and-html-displayfor-at-the-same-time-not-right-but-it-descri*@
                    @Html.ActionLink(world.WorldName, "WorldDetails/" + world.WorldId, "World") @Html.ActionLink("Delete", "DeleteWorld", new {id = world.WorldId})
                    <br />

                }
            </div>

            @*GALLERY TAB*@
            <div class="tab-pane fade" id="nav-gallery" role="tabpanel" aria-labelledby="nav-gallery-tab">...</div>
        </div>
    </div>
</div>

WorldBuilder/Views/Creator/List.cshtml
@model IEnumerable<WorldBuilder.Models.Creator>
@* Referenced from Christine's Code *@

@{
    ViewBag.Title = "Creator List";
}

<div>
    <h1>@ViewBag.Title</h1>
    @* Create a table for displaying creators *@
    <table class="table">
        <tr>
            <th>
                @* Only display creator's display name in the list view. *@
                Creator Display Name
            </th>
        </tr>

        @* Foreach loop to loop through Creator List. Again, referenced Christine's code *@
        @foreach (var creator in Model)
        {
        <tr>
            <td>
                @* Create dynamic link to the creator's profile view *@
                @*https://stackoverflow.com/questions/9584673/html-actionlink-and-html-displayfor-at-the-same-time-not-right-but-it-descri*@
                <a href="@Url.Action("CreatorProfile", "Creator", new { id=creator.CreatorId})">
                    @Html.DisplayFor(modelItem => creator.CreatorDispName)
                </a>
            </td>
        </tr>
        }
    </table>

</div>